name: Flutter Deploy

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch (adjust as needed)

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    environment: webenv

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Create .env file
        run: |
          echo BACKEND_URL=${{ secrets.BACKEND_URL }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo CONTENT_TYPE=${{ env.CONTENT_TYPE }} >> .env
          echo ACCEPT=${{ env.ACCEPT }} >> .env
          echo MEDIA_TYPE=${{ env.MEDIA_TYPE }} >> .env

      - name: Use .env file
        run: |
          source .env
          echo $BACKEND_URL
          echo $GOOGLE_CLIENT_ID
          echo $CONTENT_TYPE
          echo $ACCEPT
          echo $MEDIA_TYPE

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          flutter-version: 3.22.0-0.1.pre

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Clean build directory (optional)
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: excelmap  # Name for your artifact
          path: build/web  # Path to your built web app files

      - name: Deploy to GitHub Pages
        id: deployment  # Assign an ID for referencing outputs
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: excelmap # Reference uploaded artifact
          # ... other deployment options (optional)

      - name: Print Deployment URL
        run: |
          echo "**Deployment URL:** ${{ steps.deployment.outputs.page_url }}"
