name: Flutter Deploy

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch (adjust as needed)

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    environment: webenv

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          flutter-version: 3.22.0-0.1.pre

      - name: Install dependencies
        run: flutter pub get

      - name: Set up secrets
        uses: SpicyPizza/create-envfile@v2.0
        env:
          envkey_BACKEND_URL: ${{ secrets.BACKEND_URL }}  # Replace with your secret name
          envkey_CONTENT_TYPE: ${{ secrets.CONTENT_TYPE }}
          envkey_HTTP_METHOD: ${{ secrets.HTTP_METHOD }}
          envkey_ACCEPT: ${{ secrets.ACCEPT }}
          directory: assets
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          # Add other secrets as needed

      - name: Build web app
        run: flutter build web

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-app  # Name for your artifact
          path: build/web  # Path to your built web app files

      - name: Deploy to GitHub Pages
        id: deployment  # Assign an ID for referencing outputs
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: built-app # Reference uploaded artifact
          # ... other deployment options (optional)

      - name: Print Deployment URL
        run: |
          echo "**Deployment URL:** ${{ steps.deployment.outputs.page_url }}"
