name: Flutter Deploy

on:
  push:
    branches: [ master ]  # Trigger on pushes to the main branch (adjust as needed)

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Replace with your preferred runner

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          flutter-version: 3.22.0-0.1.pre

      - name: Install dependencies
        run: flutter pub get

      - name: Set up secrets
        uses: SpicyPizza/create-envfile@v2.0
        env:
          envkey_BACKEND_URL: ${{ secrets.BACKEND_URL }}  # Replace with your secret name
          envkey_CONTENT_TYPE: ${{ secrets.CONTENT_TYPE }}
          envkey_HTTP_METHOD: ${{ secrets.HTTP_METHOD }}
          envkey_ACCEPT: ${{ secrets.ACCEPT }}
          directory: assets
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          # Add other secrets as needed

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v4
        with:
            name: web-release-2
            path: ./build/web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: web-release-2
          token: ${{ secrets.GITHUB_TOKEN }}